name: cuidapet_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter


  
  
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  equatable: ^2.0.5
  flutter_typeahead: ^4.6.2

  json_annotation: ^4.8.1
  flutter_screenutil: ^5.8.4
  sqflite: ^2.3.0
  synchronized: ^3.1.0
  path: ^1.8.3
  nil: ^1.1.1
  
  loading_animation_widget: ^1.2.0+4
  
  validatorless: ^1.2.3
  top_snackbar_flutter: ^3.1.0
  intl: ^0.19.0
  url_launcher: ^6.2.3

  flutter_dotenv: ^5.1.0
  

  ### RiverPode Packages 
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  asyncstate: ^2.1.0


  ## Secure e share preference
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

    
  ##Firebase
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.16.0
  firebase_remote_config: ^4.3.8
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.2.1  
  google_maps_flutter: ^2.5.3
  google_places: 
    git:
      url: https://github.com/caneto/google_place.git 
      
  #google_place: ^0.4.7     

  geocoding: ^2.1.0
  geolocator: ^9.0.2

  #FaceBook
  #flutter_facebook_auth: ^5.0.11

  cupertino_icons: ^1.0.6

dependency_overrides:
  http: ">=1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  
  ## RiverPod Dependencies
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7
  riverpod_generator: ^2.3.9
  
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf